#!/usr/bin/env bash

set -euo pipefail

go run ci/version-is-bumped.go || true

if [[ "${IGNORE_PRECOMMIT_HOOK:-}" = true ]]; then
    exit 0
fi

go test ./pakang/
ci/test-behaviours.sh

if git grep -n "FIXME:TODO" | grep -v ci/githooks/pre-commit ; then
    echo "WARNING -- tags for incomplete work found"
fi

./build.sh
