#!/usr/bin/env bash

set -euo pipefail

if ! go run ci/version-is-bumped.go; then
    echo "(( warn: Bump the version string to newer than the last tagged version! ))"
fi

if [[ "${IGNORE_PRECOMMIT_HOOK:-}" = true ]]; then
    exit 0
fi

go test ./pakang/
./build.sh
